global:
  checkNewVersion: true

deployment:
  replicas: 2

securityContext:
  capabilities:
    drop: [ALL]
    add: [NET_BIND_SERVICE]
  readOnlyRootFilesystem: true
  runAsGroup: 65532
  runAsNonRoot: true
  runAsUser: 65532

ingressRoute:
  dashboard:
    enabled: true

ports:
  web:
    port: 80
    redirectTo:
      port: websecure
  websecure:
    port: 443
    tls:
      enabled: true
  metrics:
    port: 8080
    expose: true
    exposedPort: 8080

service:
  type: LoadBalancer
  spec:
    loadBalancerIP: "192.168.31.4"

metrics:
  prometheus:
    enabled: true

dashboard:
  enabled: true

readinessProbe:
  httpGet:
    path: /ping
    port: 8080
  initialDelaySeconds: 10
  periodSeconds: 10

livenessProbe:
  httpGet:
    path: /ping
    port: 8080
  initialDelaySeconds: 10
  periodSeconds: 10


