apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: first-pool-metallb
  namespace: metallb-system
spec:
  addresses:
  - 192.168.31.0/24
  - 192.168.31.4-192.168.31.9
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: default-l2-advertisement
  namespace: metallb-system
spec:
  ipAddressPools:
  - first-pool-metallb
